imports:
    - { resource: parameters.yml }
    - { resource: session.yml }
    - { resource: services.yml }

framework:
    #esi:             ~
    translator:      { fallbacks: ["%locale%"] }
    secret:          "%secret%"
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: ~
    form:            ~
    csrf_protection: ~
    validation:      { enable_annotations: true }
    #serializer:      { enable_annotations: true }
    templating:
        engines: ['twig']
    default_locale:  "%locale%"
    trusted_hosts:   ~
    trusted_proxies: ~
    session:
        handler_id: session.handler.pdo
        name: SF2SESSION
    fragments:       ~
    http_method_override: true

# Twig Configuration
twig:
    debug:            "%kernel.debug%"
    strict_variables: "%kernel.debug%"

# Assetic Configuration
assetic:
    debug:          "%kernel.debug%"
    use_controller: "%kernel.debug%"
    #bundles:        [ ]
    #java: /usr/bin/java
    filters:
        cssrewrite: ~
        #closure:
        #    jar: %kernel.root_dir%/Resources/java/compiler.jar
        yui_css:
            jar: %kernel.root_dir%/Resources/java/yuicompressor-2.4.7.jar
        yui_js:
            jar: %kernel.root_dir%/Resources/java/yuicompressor-2.4.7.jar

# Doctrine Configuration
doctrine:
    dbal:
        driver:   "%database_driver%"
        host:     "%database_host%"
        port:     "%database_port%"
        dbname:   "%database_name%"
        user:     "%database_user%"
        password: "%database_password%"
        charset:  UTF8
        # if using pdo_sqlite as your database driver:
        #   1. add the path in parameters.yml
        #     e.g. database_path: "%kernel.root_dir%/data/data.db3"
        #   2. Uncomment database_path in parameters.yml.dist
        #   3. Uncomment next line:
        #     path:     "%database_path%"

    orm:
        auto_generate_proxy_classes: "%kernel.debug%"
        naming_strategy: doctrine.orm.naming_strategy.underscore
        auto_mapping: true

doctrine_migrations:
    use_bundles: true

# Swiftmailer Configuration
swiftmailer:
    transport: "%mailer_transport%"
    host:      "%mailer_host%"
    username:  "%mailer_user%"
    password:  "%mailer_password%"
    spool:     { type: memory }

sensio_framework_extra:
    view:   {   annotations: false }
    router: {   annotations: true }

fos_rest:
    param_fetcher_listener: true
    body_listener: true
    format_listener: true
    routing_loader:
        default_format: jsonp
    view:
        view_response_listener:
            enabled: true
            force: true
        formats:
            json: true
            jsonp: true
        jsonp_handler:
            callback_param: callback
            mime_type: application/javascript
#    exception:
#        codes:
#            'AppBundle\Model\UnauthorizedException': 401
#        messages:
#            'AppBundle\Model\Exception': 404

fos_user:
    db_driver: orm
    firewall_name: main
    user_class: AppBundle\Entity\User
    group:
        group_class:   AppBundle\Entity\Group
        group_manager: sonata.user.orm.group_manager
    from_email:
        address:        no-reply@www.local
        sender_name:    wwwLocal
    registration:
        confirmation:
            enabled:    true
    service:
        mailer: fos_user.mailer.twig_swift

sonata_admin:
    title: Application

sonata_block:
    default_contexts: [cms]
    blocks:
        sonata.admin.block.admin_list:
            contexts: [admin]
        sonata.user.block.menu:    # used to display the menu in profile pages
        sonata.user.block.account: # used to display menu option (login option)
        sonata.block.service.text: # used to if you plan to use Sonata user routes

sonata_user:
    security_acl: false
    manager_type: orm
    class:
        user: AppBundle\Entity\User
        group: AppBundle\Entity\Group
    admin:
        user:
            class: AppBundle\Admin\UserAdmin
    impersonating:
        route: sonata_admin_dashboard

sonata_intl:
    timezone:
        locales:
            en_UK: Europe/London
        detectors:
            - sonata.intl.timezone_detector.locale
        default: Europe/London

vich_uploader:
    db_driver: orm

ivory_ck_editor:
    autoload: true
    jquery: true
    input_sync: true
    auto_inline: true
    default_config: app
    configs:
        app:
            toolbar: app
            uiColor: "#FFFFFF"
    toolbars:
        configs:
            app:
                - [ "Bold", "Italic", "Strike", "RemoveFormat" ]
                - "-"
                - [ "Cut", "Copy", "Paste", "PasteText", "PasteWord" ]
                - "-"
                - [ "Link", "Unlink" ]
                - "-"
                - [ "Undo", "Redo" ]
                - "-"
                - [ "Source" ]
