imports:
    - { resource: config.yml }
    - { resource: "@ApnetFunctionalTestBundle/Resources/config/config_test.yml" }

framework:
    router:
        resource: "%kernel.root_dir%/config/routing_test.yml"
