imports:
    - { resource: config.yml }
    - { resource: security.yml }
    - { resource: "@ApnetFunctionalTestBundle/Resources/config/config_test.yml" }

security:
    firewalls:
        main:
            anonymous: ~
            http_basic: ~

framework:
    router:
        resource: "%kernel.root_dir%/config/routing_test.yml"
