parameters:
    database_host:     [[DATABASE_HOST]]
    database_port:     null
    database_name:     [[DATABASE_SCHEMA]]
    database_user:     [[DATABASE_USER]]
    database_password: [[DATABASE_PASSWORD]]

    mailer_transport:  smtp
    mailer_host:       127.0.0.1
    mailer_user:       null
    mailer_password:   null

    locale:            en
    secret:            [[APP_SECRET]]

    debug_toolbar:          true
    debug_redirects:        false
    use_assetic_controller: true

    assetic_watcher_enabled: [[ASSETIC_WATCHER_ENABLED]]
